import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, RadarChart, PolarGrid, PolarAngleAxis,
  PolarRadiusAxis, Radar
} from 'recharts';
import { ArrowLeft, Sparkles, TrendingUp, AlertTriangle, CheckCircle, Info, Download } from 'lucide-react';
import InfoTooltip from './InfoTooltip';

const CHART_COLORS = ['#1a73e8', '#ff9100', '#1e8e3e', '#d93025', '#9334e6', '#12b5cb'];

const exportPDF = (analysisResult) => {
  const r = analysisResult;
  const groupRows = Object.entries(r.groupRates).map(([g, i]) =>
    `<tr><td>${g}</td><td>${i.total}</td><td>${i.favorable}</td><td>${(i.rate*100).toFixed(1)}%</td></tr>`
  ).join('');

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
<title>FairLens AI - Bias Audit Report</title>
<style>
body{font-family:'Segoe UI',sans-serif;max-width:800px;margin:0 auto;padding:40px;color:#202124}
h1{color:#1a73e8;border-bottom:2px solid #1a73e8;padding-bottom:8px}
h2{color:#3c4043;margin-top:32px}
.metric{display:inline-block;background:#f1f3f4;border-radius:8px;padding:16px 24px;margin:8px;text-align:center}
.metric .val{font-size:2rem;font-weight:700}
.metric .lbl{font-size:0.75rem;color:#5f6368;text-transform:uppercase}
.good{color:#1e8e3e}.bad{color:#d93025}.warn{color:#f9ab00}
table{width:100%;border-collapse:collapse;margin:16px 0}
th,td{padding:10px 14px;text-align:left;border-bottom:1px solid #e8eaed}
th{background:#f8f9fa;font-weight:600;font-size:0.8rem;color:#5f6368}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e8eaed;color:#9aa0a6;font-size:0.75rem}
.badge{padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:500}
.badge-pass{background:#e6f4ea;color:#1e8e3e}.badge-fail{background:#fce8e6;color:#d93025}
</style></head><body>
<h1>🔍 FairLens AI — Bias Audit Report</h1>
<p><strong>Date:</strong> ${new Date().toLocaleDateString()} · <strong>Sensitive Category:</strong> ${r.meta.sensitiveCol} · <strong>Decision Column:</strong> ${r.meta.targetCol}</p>

<h2>Fairness Score: ${r.fairnessScore}/100 <span class="${r.severity.level === 'good' ? 'good' : r.severity.level === 'warning' ? 'warn' : 'bad'}">(${r.severity.label})</span></h2>
<p>${r.severity.description}</p>

<div class="metric"><div class="val ${r.disparateImpact >= 0.8 ? 'good' : 'bad'}">${r.disparateImpact?.toFixed(3)}</div><div class="lbl">Selection Rate Ratio (Disparate Impact)</div><div><span class="badge ${r.disparateImpact >= 0.8 ? 'badge-pass' : 'badge-fail'}">${r.disparateImpact >= 0.8 ? 'PASS' : 'FAIL'}</span></div></div>
<div class="metric"><div class="val ${Math.abs(r.statisticalParityDiff) < 0.1 ? 'good' : 'bad'}">${r.statisticalParityDiff?.toFixed(4)}</div><div class="lbl">Selection Rate Difference (Statistical Parity)</div><div><span class="badge ${Math.abs(r.statisticalParityDiff) < 0.1 ? 'badge-pass' : 'badge-fail'}">${Math.abs(r.statisticalParityDiff) < 0.1 ? 'PASS' : 'FAIL'}</span></div></div>
<div class="metric"><div class="val">${r.meta.totalRows}</div><div class="lbl">Total Records</div></div>

<h2>Group Breakdown</h2>
<table><thead><tr><th>Group</th><th>Total</th><th>Favorable</th><th>Rate</th></tr></thead><tbody>${groupRows}</tbody></table>

<h2>Compliance</h2>
<table><thead><tr><th>Standard</th><th>Status</th><th>Detail</th></tr></thead><tbody>
<tr><td>EEOC 80% Rule (Selection Ratio)</td><td><span class="badge ${r.disparateImpact >= 0.8 ? 'badge-pass' : 'badge-fail'}">${r.disparateImpact >= 0.8 ? 'PASS' : 'FAIL'}</span></td><td>Ratio ${r.disparateImpact?.toFixed(3)} (threshold: 0.8)</td></tr>
<tr><td>Selection Rate Difference</td><td><span class="badge ${Math.abs(r.statisticalParityDiff) < 0.1 ? 'badge-pass' : 'badge-fail'}">${Math.abs(r.statisticalParityDiff) < 0.1 ? 'PASS' : 'FAIL'}</span></td><td>Difference ${r.statisticalParityDiff?.toFixed(4)} (threshold: ±0.1)</td></tr>
</tbody></table>

<div class="footer">Generated by FairLens AI · Bias Detection & Fairness Auditing Platform · ${new Date().toISOString()}</div>
</body></html>`;

  const w = window.open('', '_blank');
  w.document.write(html);
  w.document.close();
  setTimeout(() => { w.print(); }, 500);
};

export default function BiasReport({ analysisResult, onGetInsights, onGoBack }) {
  if (!analysisResult) {
    return (
      <div className="page-container">
        <div className="empty-state">
          <div className="empty-state-icon">
            <TrendingUp size={28} />
          </div>
          <h3>No Report Available</h3>
          <p>Run a bias analysis first to see the fairness dashboard.</p>
          <button className="btn btn-primary" onClick={onGoBack} style={{ marginTop: 16 }}>
            <ArrowLeft size={14} /> Analyze Dataset
          </button>
        </div>
      </div>
    );
  }

  const { fairnessScore, severity, disparateImpact, statisticalParityDiff, groupRates, sensitiveDistribution, targetDistribution, meta } = analysisResult;

  const barData = Object.entries(groupRates).map(([group, info]) => ({
    group,
    rate: +(info.rate * 100).toFixed(1),
    total: info.total,
    favorable: info.favorable
  }));

  const pieData = sensitiveDistribution.map(d => ({
    name: d.value, value: d.count
  }));

  const targetPieData = targetDistribution.map(d => ({
    name: d.value, value: d.count
  }));

  const radarData = [
    { metric: 'Disparate Impact', value: Math.min(disparateImpact || 0, 2) * 50, threshold: 40 },
    { metric: 'Statistical Parity', value: Math.min(Math.abs(statisticalParityDiff || 0), 1) * 100, threshold: 10 },
    { metric: 'Score', value: fairnessScore, threshold: 70 },
    { metric: 'Group Balance', value: Math.min(barData.length > 0 ? (Math.min(...barData.map(d => d.rate)) / Math.max(...barData.map(d => d.rate))) * 100 : 100, 100), threshold: 80 },
  ];

  const getScoreStyle = () => {
    if (severity.level === 'good') return { bg: 'var(--green-bg)', border: 'var(--green)', color: 'var(--green)' };
    if (severity.level === 'warning') return { bg: 'var(--yellow-bg)', border: 'var(--yellow)', color: 'var(--yellow)' };
    return { bg: 'var(--red-bg)', border: 'var(--red)', color: 'var(--red)' };
  };

  const scoreStyle = getScoreStyle();

  return (
    <div className="page-container">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h2>Bias Report</h2>
          <p>Fairness analysis for <strong>{meta.sensitiveCol}</strong> on <strong>{meta.targetCol}</strong></p>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn btn-secondary" onClick={() => exportPDF(analysisResult)} id="export-pdf-btn">
            <Download size={14} /> Export PDF
          </button>
          <button className="btn btn-primary" onClick={onGetInsights} id="get-ai-insights-btn">
            <Sparkles size={14} /> AI Insights
          </button>
        </div>
      </div>

      {/* Scorecard */}
      <div className={`scorecard ${severity.level}`} style={{ marginBottom: 24 }}>
        <div className="scorecard-score" style={{
          background: scoreStyle.bg,
          border: `2px solid ${scoreStyle.border}`
        }}>
          <span className="score-value" style={{ color: scoreStyle.color }}>{fairnessScore}</span>
        </div>
        <div className="scorecard-info">
          <h3>{severity.label}</h3>
          <p>{severity.description}</p>
        </div>
        <span className={`badge badge-${severity.level === 'good' ? 'success' : severity.level === 'warning' ? 'warning' : 'danger'}`}>
          {fairnessScore}/100
        </span>
      </div>

      {/* Metric cards */}
      <div className="metrics-grid" style={{ marginBottom: 24 }}>
        <div className={`metric-card ${disparateImpact >= 0.8 && disparateImpact <= 1.25 ? 'good' : disparateImpact >= 0.7 ? 'warning' : 'danger'}`}>
          <div className="metric-label" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, justifyContent: 'center' }}>
            Selection Rate Ratio
            <InfoTooltip text="Selection Rate Ratio (Disparate Impact) compares selection rates between groups. A ratio below 0.8 violates the EEOC 80% rule, indicating possible bias." size={12} />
          </div>
          <div className={`metric-value ${disparateImpact >= 0.8 && disparateImpact <= 1.25 ? 'good' : disparateImpact >= 0.7 ? 'warning' : 'danger'}`}>
            {disparateImpact?.toFixed(3) ?? 'N/A'}
          </div>
          <div className="metric-desc">Ideal: 1.0 · Threshold: 0.8 (80% rule)</div>
        </div>

        <div className={`metric-card ${Math.abs(statisticalParityDiff) < 0.1 ? 'good' : Math.abs(statisticalParityDiff) < 0.2 ? 'warning' : 'danger'}`}>
          <div className="metric-label" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, justifyContent: 'center' }}>
            Selection Rate Difference
            <InfoTooltip text="Selection Rate Difference (Statistical Parity) is the percentage point gap in selection rates. Ideally close to 0.0; gaps beyond ±0.1 (10%) are significant." size={12} />
          </div>
          <div className={`metric-value ${Math.abs(statisticalParityDiff) < 0.1 ? 'good' : Math.abs(statisticalParityDiff) < 0.2 ? 'warning' : 'danger'}`}>
            {statisticalParityDiff?.toFixed(4) ?? 'N/A'}
          </div>
          <div className="metric-desc">Ideal: 0.0 · Threshold: ±0.1</div>
        </div>

        <div className="metric-card neutral">
          <div className="metric-label">Total Records</div>
          <div className="metric-value neutral">{meta.totalRows.toLocaleString()}</div>
          <div className="metric-desc">Groups: {Object.keys(groupRates).length}</div>
        </div>

        <div className="metric-card neutral">
          <div className="metric-label" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, justifyContent: 'center' }}>
            Advantaged Group
            <InfoTooltip text="The demographic group that receives the highest favorable selection rate in the dataset." size={12} />
          </div>
          <div className="metric-value neutral" style={{ fontSize: '1.25rem' }}>{meta.privilegedValue}</div>
          <div className="metric-desc">Rate: {(groupRates[meta.privilegedValue]?.rate * 100 || 0).toFixed(1)}%</div>
        </div>
      </div>

      {/* Charts */}
      <div className="charts-grid" style={{ marginBottom: 24 }}>
        {/* Bar chart */}
        <div className="card">
          <div className="card-header">
            <span className="card-title">Selection Rate by Group</span>
          </div>
          <div className="chart-container" style={{ height: 280 }}>
            <ResponsiveContainer>
              <BarChart data={barData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                <XAxis dataKey="group" tick={{ fontSize: 12, fill: '#6b7280' }} />
                <YAxis tick={{ fontSize: 12, fill: '#6b7280' }} unit="%" />
                <Tooltip
                  contentStyle={{
                    background: '#fff', border: '1px solid #e5e7eb',
                    borderRadius: 6, fontSize: 13
                  }}
                />
                <Bar dataKey="rate" name="Selection Rate (%)" radius={[4, 4, 0, 0]}>
                  {barData.map((_, i) => (
                    <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Radar chart */}
        <div className="card">
          <div className="card-header">
            <span className="card-title">Fairness Overview</span>
          </div>
          <div className="chart-container" style={{ height: 280 }}>
            <ResponsiveContainer>
              <RadarChart data={radarData}>
                <PolarGrid stroke="#e5e7eb" />
                <PolarAngleAxis dataKey="metric" tick={{ fontSize: 11, fill: '#6b7280' }} />
                <PolarRadiusAxis angle={30} domain={[0, 100]} tick={{ fontSize: 10 }} />
                <Radar name="Score" dataKey="value" stroke="#0d9488" fill="#0d9488" fillOpacity={0.15} strokeWidth={2} />
                <Radar name="Threshold" dataKey="threshold" stroke="#d1d5db" fill="none" strokeDasharray="5 5" />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Sensitive distribution pie */}
        <div className="card">
          <div className="card-header">
            <span className="card-title">{meta.sensitiveCol} Distribution</span>
          </div>
          <div className="chart-container" style={{ height: 260 }}>
            <ResponsiveContainer>
              <PieChart>
                <Pie data={pieData} cx="50%" cy="50%" outerRadius={90} innerRadius={40} dataKey="value" nameKey="name" label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`} labelLine={false} style={{ fontSize: 11 }}>
                  {pieData.map((_, i) => (
                    <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Target distribution pie */}
        <div className="card">
          <div className="card-header">
            <span className="card-title">{meta.targetCol} Distribution</span>
          </div>
          <div className="chart-container" style={{ height: 260 }}>
            <ResponsiveContainer>
              <PieChart>
                <Pie data={targetPieData} cx="50%" cy="50%" outerRadius={90} innerRadius={40} dataKey="value" nameKey="name" label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`} labelLine={false} style={{ fontSize: 11 }}>
                  {targetPieData.map((_, i) => (
                    <Cell key={i} fill={CHART_COLORS[(i + 2) % CHART_COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Group Breakdown Table */}
      <div className="card" style={{ marginBottom: 24 }}>
        <div className="card-header">
          <span className="card-title">Group Breakdown</span>
        </div>
        <div className="table-wrapper">
          <table className="data-table">
            <thead>
              <tr>
                <th>Group</th>
                <th>Total</th>
                <th>Favorable</th>
                <th>Unfavorable</th>
                <th>Rate</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {barData.map(row => {
                const isPass = (row.rate / 100) >= (groupRates[meta.privilegedValue]?.rate || 0) * 0.8;
                return (
                  <tr key={row.group}>
                    <td><strong>{row.group}</strong></td>
                    <td>{row.total.toLocaleString()}</td>
                    <td>{row.favorable.toLocaleString()}</td>
                    <td>{(row.total - row.favorable).toLocaleString()}</td>
                    <td className="font-mono">{row.rate}%</td>
                    <td>
                      {row.group === meta.privilegedValue
                        ? <span className="badge badge-neutral">Reference</span>
                        : isPass
                        ? <span className="badge badge-success"><CheckCircle size={10} /> Fair</span>
                        : <span className="badge badge-danger"><AlertTriangle size={10} /> Bias</span>
                      }
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* Metric Details */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        <div className="bias-detail-card">
          <div className="bias-detail-header">
            <span className="card-title" style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Info size={14} /> Selection Rate Ratio (Disparate Impact)</span>
            <span className={`badge badge-${disparateImpact >= 0.8 ? 'success' : 'danger'}`}>
              {disparateImpact >= 0.8 ? 'Pass' : 'Fail'}
            </span>
          </div>
          <div className="bias-detail-body">
            <p className="text-sm text-secondary" style={{ marginBottom: 8 }}>
              <strong>Formula:</strong> <code>Underrepresented Group Rate / Advantaged Group Rate</code>
            </p>
            <p className="text-xs text-tertiary" style={{ marginBottom: 8, fontStyle: 'italic' }}>
              Technical details: P(favorable outcome | unprivileged group) / P(favorable outcome | privileged group)
            </p>
            <p className="text-sm text-secondary">
              A ratio below 0.8 (80%) indicates a potential compliance risk under the EEOC Four-Fifths Rule, meaning the underrepresented group is selected at a significantly lower rate than the advantaged group. Values between 0.8 and 1.25 are considered fair.
            </p>
          </div>
        </div>

        <div className="bias-detail-card">
          <div className="bias-detail-header">
            <span className="card-title" style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Info size={14} /> Selection Rate Difference (Statistical Parity)</span>
            <span className={`badge badge-${Math.abs(statisticalParityDiff) < 0.1 ? 'success' : 'danger'}`}>
              {Math.abs(statisticalParityDiff) < 0.1 ? 'Pass' : 'Fail'}
            </span>
          </div>
          <div className="bias-detail-body">
            <p className="text-sm text-secondary" style={{ marginBottom: 8 }}>
              <strong>Formula:</strong> <code>Underrepresented Group Rate − Advantaged Group Rate</code>
            </p>
            <p className="text-xs text-tertiary" style={{ marginBottom: 8, fontStyle: 'italic' }}>
              Technical details: P(favorable outcome | unprivileged group) - P(favorable outcome | privileged group)
            </p>
            <p className="text-sm text-secondary">
              The absolute difference in selection rates. A difference of 0% means both groups are selected at exactly the same rate. Differences wider than ±10% (±0.1) are generally considered significant and suggest potential unfairness.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
